"""
Django settings for rare_wms project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    # Project root .env (docker-compose env_file) then backend/.env
    load_dotenv(BASE_DIR.parent / '.env')
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@i=p2%lvl8ym9s(_#qqm24dt(6)h9(1!xjg!zhotjqc1_an$kw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['rare.netscoretech.com', 'testdr-68f74b9b66be.herokuapp.com', 'localhost','*']

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://rare.netscoretech.com",
    "https://testdr-68f74b9b66be.herokuapp.com",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Application definition

INSTALLED_APPS = [
    'dr_dashboard',
    'dashboard',
    'dashboard_meta',
    'data_ingestion',
    'ai_engine',
    'keycloak_auth',
    'strawberry_django',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'keycloak_auth.middleware.KeycloakAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rare_wms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rare_wms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
import os
import dj_database_url
from urllib.parse import quote_plus


def _postgres_url_from_components() -> str | None:
    """
    Build postgresql:// from POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST,
    POSTGRES_PORT, POSTGRES_DB. Password is URL-encoded so @ and other chars work.
    """
    user = os.getenv("POSTGRES_USER")
    if not user:
        return None
    password = os.getenv("POSTGRES_PASSWORD", "")
    host = os.getenv("POSTGRES_HOST", "localhost")
    port = os.getenv("POSTGRES_PORT", "5432")
    db = os.getenv("POSTGRES_DB", "postgres")
    return (
        f"postgresql://{quote_plus(user)}:{quote_plus(password)}"
        f"@{host}:{port}/{db}"
    )


# Prefer WMS_DATABASE_URL / DR_DATABASE_URL; else POSTGRES_*; else local dev default
WMS_DATABASE_URL = os.getenv("WMS_DATABASE_URL") or _postgres_url_from_components()
if not WMS_DATABASE_URL:
    WMS_DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/analytics_dashboard"

DR_DATABASE_URL = os.getenv("DR_DATABASE_URL") or WMS_DATABASE_URL

# APScheduler: periodic WMS + DR fetch (see dashboard.background_thread).
# Set ENABLE_BACKGROUND_SCHEDULER=1 in .env to enable (off by default for analytics stack).
_bg_sched = os.getenv("ENABLE_BACKGROUND_SCHEDULER", "false").strip().lower()
ENABLE_BACKGROUND_SCHEDULER = _bg_sched in ("1", "true", "yes", "on")

DATABASES = {
    'default': dj_database_url.config(default=WMS_DATABASE_URL),
}

# DR dashboard models: same cluster as default, optional separate schema (see DR_DATABASE_SEARCH_PATH)
_dr = dj_database_url.parse(DR_DATABASE_URL)
_dr.setdefault('OPTIONS', {})
# Use "public" for a fresh local DB; use "rare_dr,public" if that schema exists (legacy WMS)
_dr_search = os.getenv("DR_DATABASE_SEARCH_PATH", "public")
_dr['OPTIONS']['options'] = f'-c search_path={_dr_search}'
DATABASES['dr_database'] = _dr

# Database routing for apps (using schemas)
DATABASE_ROUTERS = ['rare_wms.database_router.DatabaseRouter']
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Vite production output — only listed when the folder exists (avoids staticfiles.W004)
_react_dist_default = os.path.join(BASE_DIR, '..', 'new_fronend', 'dist')
# Docker: set REACT_BUILD_DIR=/app/frontend_dist when dist is bind-mounted (see docker-compose)
REACT_BUILD_DIR = os.getenv('REACT_BUILD_DIR') or _react_dist_default
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
if os.path.isdir(REACT_BUILD_DIR):
    STATICFILES_DIRS.append(REACT_BUILD_DIR)

# Shown when dist/ is missing: local dev usually uses Vite on this URL instead of :8000
FRONTEND_DEV_URL = os.environ.get('FRONTEND_DEV_URL', 'http://localhost:5173')

# When no SPA files exist, GET / redirects to Vite (set false to see the HTML explainer page)
FRONTEND_ROOT_REDIRECT = os.getenv('FRONTEND_ROOT_REDIRECT', 'true').strip().lower() in (
    '1',
    'true',
    'yes',
    'on',
)


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


INSTALLED_APPS += ["corsheaders"]
MIDDLEWARE = ["corsheaders.middleware.CorsMiddleware"] + MIDDLEWARE
CORS_ALLOW_ALL_ORIGINS = True

# Force HTTPS in production
SECURE_SSL_REDIRECT = False  # Set to True if you have SSL termination at the server level
USE_TZ = True

# Configure protocol for pagination URLs
if 'rare.netscoretech.com' in ALLOWED_HOSTS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Media files (uploaded datasets)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Directory where uploaded CSV/Excel files are stored before loading into PG
FILE_UPLOAD_DIR = os.getenv('FILE_UPLOAD_DIR', os.path.join(BASE_DIR, 'media', 'uploads'))

# Redis — async job queue (replaces Kafka) + result caching
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Topic names (kept the same — now Redis Stream keys)
REDIS_TOPICS = {
    'FILE_UPLOADED': 'file-uploaded',
    'DB_CONNECTED': 'db-connected',
    'AI_INSIGHTS': 'ai-insights',
    'AI_WIDGET_BUILD': 'ai-widget-build',
    'AI_NL_QUERY': 'ai-nl-query',
    'AI_GRAPH_SUGGESTIONS': 'ai-graph-suggestions',
}

# Ollama / LLM configuration (OpenAI-compatible)
LLM_BASE_URL = os.getenv('LLM_BASE_URL', 'http://localhost:11434/v1')
LLM_API_KEY = os.getenv('LLM_API_KEY', 'ollama')
LLM_MODEL = os.getenv('LLM_MODEL', 'qwen2.5-coder:7b')
LLM_SUMMARY_MODEL = os.getenv('LLM_SUMMARY_MODEL', 'llama3.2:3b')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ---------------------------------------------------------------------------
# Keycloak / SSO Configuration
# Values can be overridden via environment variables (see .env.example).
# ---------------------------------------------------------------------------
_kc_server = os.getenv("KEYCLOAK_SERVER_URL", "http://localhost:8080")
_kc_realm  = os.getenv("KEYCLOAK_REALM", "master")
KEYCLOAK = {
    "SERVER_URL":       _kc_server,
    "REALM":            _kc_realm,
    "CLIENT_ID":        os.getenv("KEYCLOAK_CLIENT_ID", "analytics-dashboard"),
    "CLIENT_SECRET":    os.getenv("KEYCLOAK_CLIENT_SECRET", ""),
    "ADMIN_USERNAME":   os.getenv("KEYCLOAK_ADMIN_USERNAME", "admin"),
    "ADMIN_PASSWORD":   os.getenv("KEYCLOAK_ADMIN_PASSWORD", "admin"),
    "DISCOVERY_URL":    os.getenv(
        "KEYCLOAK_DISCOVERY_URL",
        f"{_kc_server}/realms/{_kc_realm}/.well-known/openid-configuration",
    ),
}

# Set to "true" to require valid tokens on all /api/* endpoints
KEYCLOAK_ENFORCE_API_AUTH = os.getenv("KEYCLOAK_ENFORCE_API_AUTH", "false")
