"""
Django settings for rare_wms project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@i=p2%lvl8ym9s(_#qqm24dt(6)h9(1!xjg!zhotjqc1_an$kw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['rare.netscoretech.com', 'testdr-68f74b9b66be.herokuapp.com', 'localhost','*']

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://rare.netscoretech.com",
    "https://testdr-68f74b9b66be.herokuapp.com",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Application definition

INSTALLED_APPS = [
    'dr_dashboard',
    'dashboard',
    'dashboard_meta',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rare_wms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rare_wms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
import os
import dj_database_url
from urllib.parse import quote_plus
username = "netscore"
password = "NetScore@123"

# encoded_username = quote_plus(username)
# encoded_password = quote_plus(password)
# WMS Database
WMS_DATABASE_URL = os.getenv("WMS_DATABASE_URL", "postgresql://netscore_wms_rare:NetScore@123@192.168.1.26:5432/netscore_wms_rare")

# DR Dashboard Database (using same database with different schema)
DR_DATABASE_URL = os.getenv("DR_DATABASE_URL", "postgresql://netscore_wms_rare:NetScore@123@192.168.1.26:5432/netscore_wms_rare")

DATABASES = {
    'default': dj_database_url.config(default=WMS_DATABASE_URL),  # WMS database (public schema)
    'dr_database': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'netscore_wms_rare',
        'USER': 'netscore_wms_rare',
        'PASSWORD': 'NetScore@123',
        'HOST': '192.168.1.26',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=rare_dr,public'
        }
    }
}

# Database routing for apps (using schemas)
DATABASE_ROUTERS = ['rare_wms.database_router.DatabaseRouter']
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


import os
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# React build files (Vite output; copied to staticfiles via collectstatic)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, '..', 'new_fronend', 'dist'),
]

# Served by FrontendAppView when index.html is not yet in STATIC_ROOT
REACT_BUILD_DIR = os.path.join(BASE_DIR, '..', 'new_fronend', 'dist')


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


INSTALLED_APPS += ["corsheaders"]
MIDDLEWARE = ["corsheaders.middleware.CorsMiddleware"] + MIDDLEWARE
CORS_ALLOW_ALL_ORIGINS = True

# Force HTTPS in production
SECURE_SSL_REDIRECT = False  # Set to True if you have SSL termination at the server level
USE_TZ = True

# Configure protocol for pagination URLs
if 'rare.netscoretech.com' in ALLOWED_HOSTS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
