# Generated by Django 5.2.3 on 2025-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersAssignedToDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.TextField()),
                ('documentno', models.TextField(unique=True)),
                ('customer_or_supplier', models.TextField()),
                ('createdFrom', models.TextField()),
                ('loadplan', models.TextField()),
            ],
            options={
                'db_table': 'rare_dr.dr_orders_assigned_to_drivers',
            },
        ),
        migrations.CreateModel(
            name='OrdersPendingDeliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentno', models.TextField(unique=True)),
                ('status', models.TextField(default='Pending')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rare_dr.dr_orders_pending_deliveries',
            },
        ),
        migrations.CreateModel(
            name='PodUpdatedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadplan', models.TextField()),
                ('deliveredBy', models.TextField()),
                ('transactionDate', models.TextField()),
                ('deliveryStatus', models.TextField()),
                ('documentno', models.TextField(unique=True)),
                ('deliveryTime', models.TextField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('pod1', models.TextField()),
                ('pod2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rare_dr.dr_pod_updated_orders',
            },
        ),
        migrations.CreateModel(
            name='TotalLoadPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadplan', models.TextField(unique=True)),
                ('deliverydate', models.TextField()),
                ('location', models.TextField()),
                ('driver', models.TextField()),
                ('noOfOrders', models.TextField()),
                ('warehouse', models.TextField()),
                ('totalStops', models.TextField(blank=True, null=True)),
                ('lpStatus', models.TextField()),
                ('truckType', models.TextField(blank=True, null=True)),
                ('truckWeight', models.TextField()),
                ('totalLpWeight', models.TextField()),
            ],
            options={
                'db_table': 'rare_dr.dr_total_load_plans',
            },
        ),
        migrations.CreateModel(
            name='TotalReturnOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.TextField()),
                ('documentno', models.TextField(unique=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('customer', models.TextField()),
                ('date', models.TextField()),
                ('createdFrom', models.TextField()),
                ('location', models.TextField()),
                ('returnNotes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rare_dr.dr_total_return_orders',
            },
        ),
    ]
