# Generated by Django 5.1.6 on 2025-09-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordersassignedtodrivers',
            table='dr_orders_assigned_to_drivers',
        ),
        migrations.AlterModelTable(
            name='orderspendingdeliveries',
            table='dr_orders_pending_deliveries',
        ),
        migrations.AlterModelTable(
            name='podupdatedorders',
            table='dr_pod_updated_orders',
        ),
        migrations.AlterModelTable(
            name='totalloadplans',
            table='dr_total_load_plans',
        ),
        migrations.AlterModelTable(
            name='totalreturnorders',
            table='dr_total_return_orders',
        ),
    ]
