# Generated by Django 5.1.6 on 2025-09-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr_dashboard', '0002_alter_ordersassignedtodrivers_table_and_more'),
    ]

    operations = [
    ]
