# Generated by Django 5.1.6 on 2025-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_dashboard', '0003_auto_20250909_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalreturnorders',
            name='documentText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podupdatedorders',
            name='driver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podupdatedorders',
            name='driverId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
