# Generated by Django 5.2.3 on 2025-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_dashboard', '0004_auto_20250909_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersassignedtodrivers',
            name='billingCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersassignedtodrivers',
            name='deliveryStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersassignedtodrivers',
            name='driverId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersassignedtodrivers',
            name='shippingCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalloadplans',
            name='driverId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
