# Generated by Django 5.2.3 on 2026-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_dashboard', '0005_ordersassignedtodrivers_billingcity_and_more'),
    ]

    operations = [
        # Table dr_total_sales_orders already exists in this DB; only update Django state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TotalSalesOrders',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('documentno', models.TextField(unique=True)),
                        ('customer', models.TextField()),
                        ('location', models.TextField()),
                        ('status', models.TextField(blank=True, null=True)),
                        ('shippingAddress', models.TextField(blank=True, null=True)),
                        ('created_date', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'dr_total_sales_orders',
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql="SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # Postgres already has lowercase column names; only sync Django's migration state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='ordersassignedtodrivers',
                    old_name='billingCity',
                    new_name='billingcity',
                ),
                migrations.RenameField(
                    model_name='ordersassignedtodrivers',
                    old_name='deliveryStatus',
                    new_name='deliverystatus',
                ),
                migrations.RenameField(
                    model_name='ordersassignedtodrivers',
                    old_name='driverId',
                    new_name='shippingaddress',
                ),
                migrations.RenameField(
                    model_name='ordersassignedtodrivers',
                    old_name='shippingCity',
                    new_name='shippingcity',
                ),
                migrations.RenameField(
                    model_name='totalloadplans',
                    old_name='driverId',
                    new_name='driverid',
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql="SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # Column already exists in DB; only sync Django state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordersassignedtodrivers',
                    name='created_date',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql="SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        migrations.AlterField(
            model_name='podupdatedorders',
            name='deliveryTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='podupdatedorders',
            name='transactionDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='totalloadplans',
            name='deliverydate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='totalreturnorders',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
