# Generated by Django 5.2.3 on 2025-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranId', models.TextField(unique=True)),
                ('createdFrom', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('vendor', models.TextField()),
                ('tranDate', models.DateField()),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranId', models.TextField(unique=True)),
                ('location', models.TextField()),
                ('customer', models.TextField()),
                ('related_purchase', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateField()),
                ('shipDate', models.DateField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('shipMethod', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackedOrPickedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdFrom', models.TextField(blank=True, null=True)),
                ('documentNumber', models.TextField()),
                ('customer', models.TextField()),
                ('packer', models.TextField(blank=True, null=True)),
                ('picker', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('shipDate', models.DateField()),
                ('dateCreated', models.DateTimeField()),
                ('packedTime', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalOrdersReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.TextField()),
                ('createdFrom', models.TextField()),
                ('createdDate', models.DateField()),
                ('tranId', models.TextField(unique=True)),
                ('receivedBy', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
