# Generated by Django 5.2.3 on 2025-07-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensalesorder',
            name='createdFrom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packedorpickedorder',
            name='documentNumber',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='totalordersreceived',
            name='supplier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
