# Generated by Django 5.1.6 on 2025-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_opensalesorder_createdfrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensalesorder',
            name='createdFrom',
        ),
        migrations.AlterField(
            model_name='packedorpickedorder',
            name='documentNumber',
            field=models.TextField(),
        ),
    ]
