# Generated by Django 5.1.6 on 2025-11-07 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_opensalesorder_createdfrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.TextField(unique=True)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_adjustment_data',
            },
        ),
        migrations.CreateModel(
            name='InventoryCountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.TextField(unique=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_count_data',
            },
        ),
        migrations.CreateModel(
            name='PendingApprovalInventoryAdjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, null=True)),
                ('account', models.TextField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pending_approval_inventory_adjustments',
            },
        ),
        migrations.CreateModel(
            name='PendingApprovalInventoryCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.TextField(unique=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pending_approval_inventory_counts',
            },
        ),
        migrations.CreateModel(
            name='ReOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reorderPoint', models.IntegerField(blank=True, null=True)),
                ('quantityAvailable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_order_items',
            },
        ),
        migrations.AddField(
            model_name='totalordersreceived',
            name='purchaseCreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalordersreceived',
            name='supplier',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('quantity', models.TextField(blank=True, null=True)),
                ('inventoryAdjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.inventoryadjustmentdata')),
            ],
            options={
                'db_table': 'inventory_adjustment_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('binNumber', models.TextField(blank=True, null=True)),
                ('inventoryCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.inventorycountdata')),
            ],
            options={
                'db_table': 'inventory_count_items',
            },
        ),
        migrations.CreateModel(
            name='PendingApprovalInventoryCountItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('binNumber', models.TextField(blank=True, null=True)),
                ('pendingApprovalInventoryCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.pendingapprovalinventorycounts')),
            ],
            options={
                'db_table': 'pending_approval_inventory_count_items',
            },
        ),
    ]
