# Generated by Django 5.2.3 on 2025-11-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_inventoryadjustmentdata_inventorycountdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('empImage', models.BinaryField(blank=True, db_column='emp_image', null=True)),
            ],
            options={
                'db_table': 'employee_details',
            },
        ),
        migrations.CreateModel(
            name='ItemsFromFulfillments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(blank=True, db_column='date_created', null=True)),
                ('documentNumber', models.TextField(blank=True, db_column='document_number', null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items_from_fulfillments',
            },
        ),
        migrations.CreateModel(
            name='ItemsFromReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(blank=True, db_column='date_created', null=True)),
                ('documentNumber', models.TextField(blank=True, db_column='document_number', null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items_from_receipts',
            },
        ),
        migrations.CreateModel(
            name='TransactionsCreatedByWMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True)),
                ('documentNumber', models.TextField(db_column='document_number', unique=True)),
                ('dateCreated', models.DateTimeField(blank=True, db_column='date_created', null=True)),
            ],
            options={
                'db_table': 'transactions_created_by_wms',
            },
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentdata',
            name='createdBy',
            field=models.TextField(blank=True, db_column='created_by', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentdata',
            name='dateCreated',
            field=models.DateTimeField(blank=True, db_column='date_created', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentdata',
            name='documentNumber',
            field=models.TextField(db_column='document_number', unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentitems',
            name='inventoryAdjustment',
            field=models.ForeignKey(db_column='inventory_adjustment_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.inventoryadjustmentdata'),
        ),
        migrations.AlterField(
            model_name='inventorycountdata',
            name='createdBy',
            field=models.TextField(blank=True, db_column='created_by', null=True),
        ),
        migrations.AlterField(
            model_name='inventorycountdata',
            name='dateCreated',
            field=models.DateTimeField(blank=True, db_column='date_created', null=True),
        ),
        migrations.AlterField(
            model_name='inventorycountdata',
            name='documentNumber',
            field=models.TextField(db_column='document_number', unique=True),
        ),
        migrations.AlterField(
            model_name='inventorycountitems',
            name='binNumber',
            field=models.TextField(blank=True, db_column='bin_number', null=True),
        ),
        migrations.AlterField(
            model_name='inventorycountitems',
            name='inventoryCount',
            field=models.ForeignKey(db_column='inventory_count_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.inventorycountdata'),
        ),
        migrations.AlterField(
            model_name='pendingapprovalinventoryadjustments',
            name='createdBy',
            field=models.TextField(blank=True, db_column='created_by', null=True),
        ),
        migrations.AlterField(
            model_name='pendingapprovalinventoryadjustments',
            name='dateCreated',
            field=models.DateTimeField(blank=True, db_column='date_created', null=True),
        ),
        migrations.AlterField(
            model_name='pendingapprovalinventorycountitems',
            name='binNumber',
            field=models.TextField(blank=True, db_column='bin_number', null=True),
        ),
        migrations.AlterField(
            model_name='pendingapprovalinventorycountitems',
            name='pendingApprovalInventoryCount',
            field=models.ForeignKey(db_column='pending_approval_inventory_count_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.pendingapprovalinventorycounts'),
        ),
        migrations.AlterField(
            model_name='pendingapprovalinventorycounts',
            name='createdBy',
            field=models.TextField(blank=True, db_column='created_by', null=True),
        ),
        migrations.AlterField(
            model_name='pendingapprovalinventorycounts',
            name='dateCreated',
            field=models.DateTimeField(blank=True, db_column='date_created', null=True),
        ),
        migrations.AlterField(
            model_name='pendingapprovalinventorycounts',
            name='documentNumber',
            field=models.TextField(db_column='document_number', unique=True),
        ),
        migrations.AlterField(
            model_name='reorderitems',
            name='itemName',
            field=models.TextField(blank=True, db_column='item_name', null=True),
        ),
        migrations.AlterField(
            model_name='reorderitems',
            name='quantityAvailable',
            field=models.IntegerField(blank=True, db_column='quantity_available', null=True),
        ),
        migrations.AlterField(
            model_name='reorderitems',
            name='reorderPoint',
            field=models.IntegerField(blank=True, db_column='reorder_point', null=True),
        ),
    ]
